version: "3.9"

services:
  backend:
    build: ./backend
    container_name: referai-backend
    ports:
      - "8000:8000"
    environment:
      - DB_URL=${DB_URL}
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: referai-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: referai-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - "5432:5432"

volumes:
  pgdata:
